### ISSUE TITLE
'builder.openJsxLiteEditor' not found

### ISSUE THREAD

**Issue by jneeven** [BuilderIO/vscode#2]
Hello! I've installed your vscode extension and have tried to launch the editor with the vscode command, but vscode throws an error:
```
Command 'Builder.io: Open Builder.io visual editor' resulted in an error (command 'builder.openJsxLiteEditor' not found)
```

Do I need some other requirements that I may not have installed yet? I'm not familiar with debugging vscode extensions, so unfortunately I don't have more information than this error message... I'm using VSCode 1.53.2.

**Comment by steve8708** [comment]
thanks for reporting @jneeven !

I just realized we have not implemented that command just yet - removed it and publishing the the vscode extension now

you should still be able to use the "open builder.io" command to use the visual editor / import tootls and get code output, and "open jsx lite editor to the side" when you have a JSX Lite file open to edit it visually in a side panel
